version: '3.1'

services:
  db:
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ddd-example
      POSTGRES_USER: ddd-example
      POSTGRES_DB: ddd-example